### ISSUE TITLE
[S360] Use MCR containers instead

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-linux-build-agent#42]
Ref [ShaLensPrdUnscannableContainer Lens job](https://lens.msftcloudes.com/#/dashboard/23edb71e-55b0-42dd-b140-0ecc1bb77b3c?_g=(ws:e36e780f-b4f7-49f6-b1c8-a426de0d20bc)&params=(filters:!((k:AssetType,v:'Container%20Host'),(k:Cloud,v:'Public'),(k:RemediationOwner,v:'3138806a-1bad-4463-aac7-d5c6ac92eb48'),(k:SubscriptionId,v:'8afa857f-ba38-4efa-bd5b-41fc50ac5200'),(k:Environment,v:'Prod'),(k:IsActionable,v:'True'),(k:DueDateMonth,v:'2023-12-01T00:00:00.0000000Z'),(k:S360IdModification,v:''),(k:ScanType,v:'Microsoft-SecurityHealth'),(k:ScanToolName,v:'MissingScanContainerImage')),time:(from:'2023-10-09T04:21:48.2570954Z',to:'2023-10-09T17:31:26.4254801Z')))

I believe the containers being reported from the Lens job above are from this repository. We have an upcoming S360 item to onboard onto [scannable containers](https://eng.ms/docs/microsoft-security/cloud-ecosystem-security/azure-security/security-health-analytics/sha-intelligence/threat-vulnerability-management/remediate/unscannablecontainer). I'm thinking we can switch to Mariner containers if they're available.

**Comment by joaomoreno** [comment]
There was an initial effort here last year: https://github.com/microsoft/vscode-internalbacklog/issues/2937

@deepak1556 is this problem now simpler?

**Comment by rzhao271** [comment]
The query's changed now and we don't seem to have an S360 item anymore for unscannable containers.
I'm closing this issue.
